### ISSUE TITLE
Build for Apple m1 devices

### ISSUE THREAD

**Issue by last-Programmer** [JetBrains/team-explorer-everywhere#19]
Hi,
Could you please provide instructions for how to build for apple m1 devices.
Thanks

**Comment by ForNeVeR** [comment]
This is mostly a pure Java project, and requires no additional actions to be built for other CPU architectures, as far as I know. So, the build instructions are the same as for any other architectures. Please check [the Appveyor build script](https://github.com/JetBrains/team-explorer-everywhere/blob/820f70bc1d3b195286f72448e0f8eb15c9b49a0d/.appveyor.yml) for exact steps.

**Comment by last-Programmer** [comment]
Sorry i know nothing about java. Could you please tell. me how to produce tf execuable for APPLE m1 devices. If i use the release available in this repository i get the following error mentioned here https://youtrack.jetbrains.com/issue/RIDER-57683.

Do i have to download arch64 java and build this repoistory on top of that? or what should i do to fix the error mentioned above.

**Comment by ForNeVeR** [comment]
Looks like a JNA update would be required. I'm not sure what version of JNA supports M1. And it's a pretty complex process to update embedded libraries in this code, unfortunately.
