### ISSUE TITLE
JNA/JNI and other updates

### ISSUE THREAD

**Issue by eric-milles** [JetBrains/team-explorer-everywhere#35]
@ForNeVeR Would it be possible to put together a PR to move some of your changes back to the [`microsoft/team-explorer-everywhere`](https://github.com/microsoft/team-explorer-everywhere) repository?  There are a number of issues there regarding Apple M1 support.  I was able to update JNA, but I do not know where it is used.  And I lack the ability to make any changes to the native support.

* https://github.com/microsoft/team-explorer-everywhere/issues/364
* https://github.com/microsoft/team-explorer-everywhere/issues/356
* https://github.com/microsoft/team-explorer-everywhere/issues/350
* https://github.com/microsoft/team-explorer-everywhere/issues/334

**Comment by ForNeVeR** [comment]
I am so sorry, Eric, for some reason I didn't immediately see a notification about your question in this issue (normally I am much more responsive than that).

But now I did, and [sent a PR to the upstream repository](https://github.com/microsoft/team-explorer-everywhere/pull/365).

Let's proceed with discussion there.
